/* Nómina — dataset de ejemplo (10 colaboradores).
   Se siembra en localStorage la primera vez que se abre el módulo, y se puede
   volver a cargar desde el estado vacío. Borralo cuando cargues datos reales.
   Datos ficticios: nombres, clientes, proyectos, cuentas y coberturas son inventados (ISO 27001). */
window.NOMINA_DEMO = [
  {
    id: "demo-01", creado: "2026-04-06T10:00:00-03:00",
    nombre: "Martina", apellido: "Rossi", estado: "Activo", foto: "",
    documento: "32.845.109", mail: "martina.rossi@notabotagency.es", telefono: "+54 9 351 555 0184",
    direccionCompleta: "Av. Rafael Núñez 4250, Córdoba Capital, Córdoba, Argentina",
    contactoAltNombre: "Laura Rossi", contactoAltVinculo: "Hermana", contactoAltTelefono: "+54 9 351 555 0198",
    pasaporte: "AAF204118", cuit: "27-32845109-4", linkedin: "https://www.linkedin.com/in/martina-rossi",
    cliente: "Facephi", proyecto: "AI Hub", puntoContactoCliente: "Fernando Oteros", responsableNotaBot: "Fer",
    rol: "QA", dedicacion: "Full time", pais: "Argentina", inicio: "2026-04-06", ptoAcordados: 15,
    licencias: [
      { id: "l0101", tipo: "Vacaciones", desde: "2026-02-10", hasta: "2026-02-14", dias: 5, estado: "Tomada" },
      { id: "l0102", tipo: "Día de estudio / examen", desde: "2026-06-19", hasta: "2026-06-19", dias: 1, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Facephi", fechaEntrega: "2026-04-06",
      equipo: 'MacBook Pro 14" M3', nroSerie: "FVFGH31Q05MD", estado: "Asignado",
      historial: [
        { fecha: "2026-04-06", evento: 'Entrega inicial · MacBook Pro 14" (FVFGH31Q05MD)' },
        { fecha: "2026-04-06", evento: "Alta de accesos VPN y repositorios del cliente" },
      ],
    },
    seguimientos: [
      { id: "s0101", fecha: "2026-09-07", tipo: "Mensual", nota: "Conforme con el proyecto. Buena integración con el equipo.", responsable: "Fer", proximo: "2026-10-07" },
      { id: "s0102", fecha: "2026-08-05", tipo: "Mensual", nota: "Sin bloqueos. Solicita revisar objetivos del trimestre.", responsable: "Fer", proximo: "2026-09-07" },
      { id: "s0103", fecha: "2026-07-04", tipo: "Mensual", nota: "Primer mes cerrado. Se adaptó rápido al stack de QA.", responsable: "Fer", proximo: "2026-08-05" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-07", actualizadoPor: "Fer",
      motivo: "Buen desempeño e integración con el equipo.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-07",
      oportunidad: "Explorar mayor alcance con cliente",
    },
    documentos: [
      { id: "d0101", nombre: "Contrato de trabajo", tipo: "Contrato", fecha: "2026-04-06", archivo: "", archivoNombre: "contrato-martina-rossi.pdf" },
      { id: "d0102", nombre: "DNI (frente y dorso)", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-04-02", archivo: "", archivoNombre: "dni-martina-rossi.pdf" },
      { id: "d0103", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-03-20", archivo: "", archivoNombre: "cv-martina-rossi.pdf" },
      { id: "d0104", nombre: "Constancia de CBU · Banco Galicia", tipo: "Constancia de CBU", fecha: "2026-04-03", archivo: "", archivoNombre: "cbu-galicia-martina.pdf" },
    ],
    administracion: {
      legajo: "NB-0001", centroCosto: "Delivery · Facephi", modalidadPago: "Transferencia bancaria",
      banco: "Banco Galicia", cuenta: "0070999530004012345678", alias: "martina.rossi.nb",
      moneda: "ARS", remuneracion: 2450000, periodicidad: "Mensual", cobertura: "OSDE 210",
      notas: "Ajuste salarial semestral pactado (marzo / septiembre).",
    },
  },
  {
    id: "demo-02", creado: "2026-05-19T09:30:00-03:00",
    nombre: "Diego", apellido: "Ferreira", estado: "Activo", foto: "",
    documento: "4.982.331-6", mail: "diego.ferreira@notabotagency.es", telefono: "+598 99 421 337",
    direccionCompleta: "Br. España 2711, apto. 902, Pocitos, Montevideo, Uruguay",
    contactoAltNombre: "Paula Ferreira", contactoAltVinculo: "Pareja", contactoAltTelefono: "+598 99 555 210",
    pasaporte: "D0451192", cuit: "", linkedin: "https://www.linkedin.com/in/diego-ferreira",
    cliente: "Nimbus Logística", proyecto: "Portal B2B", puntoContactoCliente: "Carla Méndez", responsableNotaBot: "Joaco",
    rol: "Automation Engineer", dedicacion: "Part time", pais: "Uruguay", inicio: "2026-05-19", ptoAcordados: 14,
    licencias: [
      { id: "l0201", tipo: "Vacaciones", desde: "2026-07-14", hasta: "2026-07-18", dias: 5, estado: "Aprobada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-05-19",
      equipo: 'MacBook Air 13" M2', nroSerie: "C02XR1A2JGH6", estado: "Asignado",
      historial: [{ fecha: "2026-05-19", evento: 'Entrega inicial · MacBook Air 13"' }],
    },
    seguimientos: [
      { id: "s0201", fecha: "2026-08-28", tipo: "Mensual", nota: "Buen ritmo. Automatizó 3 flujos del portal.", responsable: "Joaco", proximo: "2026-09-28" },
      { id: "s0202", fecha: "2026-07-24", tipo: "Mensual", nota: "Cómodo con el equipo del cliente. Pidió acceso a ambiente de staging.", responsable: "Joaco", proximo: "2026-08-28" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-08-28", actualizadoPor: "Joaco",
      motivo: "Entregas en fecha, cliente conforme.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-09-28",
      oportunidad: "Proponer pasar a full time si se amplía el alcance del portal",
    },
    documentos: [
      { id: "d0201", nombre: "Contrato de servicios", tipo: "Contrato", fecha: "2026-05-19", archivo: "", archivoNombre: "contrato-diego-ferreira.pdf" },
      { id: "d0202", nombre: "Cédula de identidad", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-05-14", archivo: "", archivoNombre: "cedula-diego-ferreira.pdf" },
      { id: "d0203", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-05-02", archivo: "", archivoNombre: "cv-diego-ferreira.pdf" },
      { id: "d0204", nombre: "Constancia de inscripción DGI (monotributo)", tipo: "Alta AFIP / Monotributo", fecha: "2026-05-16", archivo: "", archivoNombre: "constancia-dgi-diego.pdf" },
      { id: "d0205", nombre: "Constancia de cuenta · Banco Itaú Uruguay", tipo: "Constancia de CBU", fecha: "2026-05-15", archivo: "", archivoNombre: "cuenta-itau-diego.pdf" },
    ],
    administracion: {
      legajo: "NB-0002", centroCosto: "Delivery · Nimbus Logística", modalidadPago: "Transferencia bancaria",
      banco: "Banco Itaú Uruguay", cuenta: "UY55 1234 0000 0000 0012 3456", alias: "diego.ferreira.nb",
      moneda: "UYU", remuneracion: 92000, periodicidad: "Mensual", cobertura: "FONASA · Médica Uruguaya",
      notas: "Factura mensual como monotributista. Pago el día 5 de cada mes.",
    },
  },
  {
    id: "demo-03", creado: "2026-06-02T11:15:00-03:00",
    nombre: "Camila", apellido: "Duarte", estado: "Activo", foto: "",
    documento: "3.221.884", mail: "camila.duarte@notabotagency.es", telefono: "+595 981 442 118",
    direccionCompleta: "Dr. Molas López 456, Villa Morra, Asunción, Paraguay",
    contactoAltNombre: "Rosa Duarte", contactoAltVinculo: "Madre", contactoAltTelefono: "+595 981 700 004",
    pasaporte: "PY0482119", cuit: "", linkedin: "https://www.linkedin.com/in/camila-duarte",
    cliente: "Faro Educación", proyecto: "Campus Online", puntoContactoCliente: "Nicolás Rivas", responsableNotaBot: "Sol",
    rol: "Data Analyst", dedicacion: "Full time", pais: "Paraguay", inicio: "2026-06-02", ptoAcordados: 15,
    licencias: [
      { id: "l0301", tipo: "Licencia médica", desde: "2026-08-11", hasta: "2026-08-12", dias: 2, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Faro Educación", fechaEntrega: "2026-06-02",
      equipo: "Dell Latitude 7440", nroSerie: "9QF7X23", estado: "Asignado",
      historial: [{ fecha: "2026-06-02", evento: "Entrega inicial · Dell Latitude 7440" }],
    },
    seguimientos: [
      { id: "s0301", fecha: "2026-09-01", tipo: "Mensual", nota: "Observaciones sobre calidad de datos del cliente. Segunda vez que aparece.", responsable: "Sol", proximo: "2026-09-15" },
      { id: "s0302", fecha: "2026-08-01", tipo: "Mensual", nota: "Pidió más contexto de negocio para los reportes.", responsable: "Sol", proximo: "2026-09-01" },
    ],
    relacion: {
      estado: "Requiere atención", ultimaActualizacion: "2026-09-01", actualizadoPor: "Sol",
      motivo: "Observaciones reiteradas sobre alcance y calidad de datos del cliente.",
      proximaAccion: "Reunión con el cliente para redefinir alcance", proximaAccionFecha: "2026-09-15",
      oportunidad: "Cerrar acuerdo de gobierno de datos con Faro Educación",
    },
    documentos: [
      { id: "d0301", nombre: "Contrato de servicios", tipo: "Contrato", fecha: "2026-06-02", archivo: "", archivoNombre: "contrato-camila-duarte.pdf" },
      { id: "d0302", nombre: "Cédula de identidad", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-05-28", archivo: "", archivoNombre: "cedula-camila-duarte.pdf" },
      { id: "d0303", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-05-15", archivo: "", archivoNombre: "cv-camila-duarte.pdf" },
      { id: "d0304", nombre: "Constancia de cuenta bancaria", tipo: "Constancia de CBU", fecha: "2026-05-29", archivo: "", archivoNombre: "cuenta-itau-camila.pdf" },
    ],
    administracion: {
      legajo: "NB-0003", centroCosto: "Data · Faro Educación", modalidadPago: "Transferencia bancaria",
      banco: "Banco Itaú Paraguay", cuenta: "800-123456-7", alias: "camila.duarte.nb",
      moneda: "USD", remuneracion: 2600, periodicidad: "Mensual", cobertura: "Seguro médico particular (Asismed)",
      notas: "Contractor. Pago vía transferencia internacional el día 5.",
    },
  },
  {
    id: "demo-04", creado: "2026-06-10T16:40:00-03:00",
    nombre: "Sebastián", apellido: "Rojas", estado: "Std By", foto: "",
    documento: "16.482.905-1", mail: "sebastian.rojas@notabotagency.es", telefono: "+56 9 6721 0043",
    direccionCompleta: "Av. Providencia 1208, of. 34, Providencia, Santiago, Región Metropolitana, Chile",
    contactoAltNombre: "Ignacio Rojas", contactoAltVinculo: "Hermano", contactoAltTelefono: "+56 9 6721 0099",
    pasaporte: "CL4820511", cuit: "", linkedin: "https://www.linkedin.com/in/sebastian-rojas",
    cliente: "Vento Media", proyecto: "Auditoría SEO Q2", puntoContactoCliente: "Paula Iglesias", responsableNotaBot: "Fer",
    rol: "Consultor SEO", dedicacion: "Part time", pais: "Chile", inicio: "2026-06-10", ptoAcordados: 12,
    licencias: [
      { id: "l0401", tipo: "Vacaciones", desde: "2026-07-21", hasta: "2026-07-23", dias: 3, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-06-10",
      equipo: 'MacBook Air 13" M2', nroSerie: "C02XV3KLMD7N", estado: "En tránsito",
      historial: [
        { fecha: "2026-06-10", evento: 'Entrega inicial · MacBook Air 13"' },
        { fecha: "2026-08-22", evento: "Retiro del equipo para reasignación (colaborador en Std By)" },
      ],
    },
    seguimientos: [
      { id: "s0401", fecha: "2026-08-20", tipo: "Puntual", nota: "Terminó la auditoría SEO. Queda a la espera de nuevo brief del cliente.", responsable: "Fer", proximo: "2026-09-20" },
      { id: "s0402", fecha: "2026-07-10", tipo: "Mensual", nota: "Avance del 60% en la auditoría. Sin bloqueos.", responsable: "Fer", proximo: "2026-08-10" },
    ],
    relacion: {
      estado: "Requiere atención", ultimaActualizacion: "2026-08-20", actualizadoPor: "Fer",
      motivo: "Sin proyecto asignado hace 3 semanas.",
      proximaAccion: "Definir nueva asignación o baja temporal", proximaAccionFecha: "2026-09-20",
      oportunidad: "Ofrecer el perfil a Aurora Retail para SEO del eCommerce",
    },
    documentos: [
      { id: "d0401", nombre: "Contrato de servicios", tipo: "Contrato", fecha: "2026-06-10", archivo: "", archivoNombre: "contrato-sebastian-rojas.pdf" },
      { id: "d0402", nombre: "Cédula de identidad (RUT)", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-06-05", archivo: "", archivoNombre: "rut-sebastian-rojas.pdf" },
      { id: "d0403", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-05-25", archivo: "", archivoNombre: "cv-sebastian-rojas.pdf" },
      { id: "d0404", nombre: "Constancia de cuenta · Banco de Chile", tipo: "Constancia de CBU", fecha: "2026-06-06", archivo: "", archivoNombre: "cuenta-bancochile-sebastian.pdf" },
    ],
    administracion: {
      legajo: "NB-0004", centroCosto: "SEO · Vento Media", modalidadPago: "Transferencia bancaria",
      banco: "Banco de Chile", cuenta: "001-234567-89", alias: "sebastian.rojas.nb",
      moneda: "CLP", remuneracion: 1650000, periodicidad: "Por entregable", cobertura: "Isapre Colmena",
      notas: "En Std By desde agosto 2026. Sin facturación mientras no haya asignación activa.",
    },
  },
  {
    id: "demo-05", creado: "2026-06-18T08:50:00-03:00",
    nombre: "Valentina", apellido: "Gómez", estado: "Activo", foto: "",
    documento: "1.014.882.331", mail: "valentina.gomez@notabotagency.es", telefono: "+57 320 448 1120",
    direccionCompleta: "Calle 70 # 11-30, apto. 501, Chapinero, Bogotá, Cundinamarca, Colombia",
    contactoAltNombre: "Andrea Gómez", contactoAltVinculo: "Hermana", contactoAltTelefono: "+57 320 448 1188",
    pasaporte: "CO7712043", cuit: "", linkedin: "https://www.linkedin.com/in/valentina-gomez",
    cliente: "Aurora Retail", proyecto: "eCommerce Revamp", puntoContactoCliente: "Diana Salas", responsableNotaBot: "Joaco",
    rol: "Diseñadora UX", dedicacion: "Full time", pais: "Colombia", inicio: "2026-06-18", ptoAcordados: 15,
    licencias: [
      { id: "l0501", tipo: "Vacaciones", desde: "2026-09-22", hasta: "2026-09-26", dias: 5, estado: "Solicitada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Aurora Retail", fechaEntrega: "2026-06-18",
      equipo: 'MacBook Pro 16" M3 Pro', nroSerie: "FVFH8K2LQ1P", estado: "Asignado",
      historial: [{ fecha: "2026-06-18", evento: 'Entrega inicial · MacBook Pro 16" + licencia Figma Organization' }],
    },
    seguimientos: [
      { id: "s0501", fecha: "2026-09-03", tipo: "Mensual", nota: "Onboarding completo. Muy buena recepción del equipo de diseño del cliente.", responsable: "Joaco", proximo: "2026-10-03" },
      { id: "s0502", fecha: "2026-08-04", tipo: "Onboarding", nota: "Semana 6. Ya lidera el rediseño del checkout.", responsable: "Joaco", proximo: "2026-09-03" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-03", actualizadoPor: "Joaco",
      motivo: "Integración muy buena, feedback positivo del cliente.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-03",
      oportunidad: "Sumar horas de research al contrato",
    },
    documentos: [
      { id: "d0501", nombre: "Contrato de servicios", tipo: "Contrato", fecha: "2026-06-18", archivo: "", archivoNombre: "contrato-valentina-gomez.pdf" },
      { id: "d0502", nombre: "Cédula de ciudadanía", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-06-12", archivo: "", archivoNombre: "cedula-valentina-gomez.pdf" },
      { id: "d0503", nombre: "Currículum vitae + portfolio", tipo: "CV", fecha: "2026-06-01", archivo: "", archivoNombre: "cv-portfolio-valentina-gomez.pdf" },
      { id: "d0504", nombre: "Certificación de cuenta · Bancolombia", tipo: "Constancia de CBU", fecha: "2026-06-13", archivo: "", archivoNombre: "cuenta-bancolombia-valentina.pdf" },
      { id: "d0505", nombre: "Diploma · Diseño Gráfico (Universidad Nacional)", tipo: "Título / Diploma", fecha: "2026-06-14", archivo: "", archivoNombre: "diploma-disenio-valentina.pdf" },
    ],
    administracion: {
      legajo: "NB-0005", centroCosto: "Diseño · Aurora Retail", modalidadPago: "Transferencia bancaria",
      banco: "Bancolombia", cuenta: "Ahorros 123-456789-01", alias: "valentina.gomez.nb",
      moneda: "COP", remuneracion: 9800000, periodicidad: "Mensual", cobertura: "EPS Sura",
      notas: "Contractor full time. Revisión de tarifa prevista para diciembre 2026.",
    },
  },
  {
    id: "demo-06", creado: "2026-06-25T13:20:00-03:00",
    nombre: "Mateo", apellido: "Herrera", estado: "Activo", foto: "",
    documento: "HEGM910412HDFRRT08", mail: "mateo.herrera@notabotagency.es", telefono: "+52 55 3410 7788",
    direccionCompleta: "Calle Orizaba 141, int. 3, Roma Norte, Ciudad de México, CDMX, México",
    contactoAltNombre: "Sofía Herrera", contactoAltVinculo: "Pareja", contactoAltTelefono: "+52 55 3410 7799",
    pasaporte: "G12984771", cuit: "", linkedin: "https://www.linkedin.com/in/mateo-herrera",
    cliente: "Delta Salud", proyecto: "Telemedicina", puntoContactoCliente: "Dra. Luciana Paz", responsableNotaBot: "Andrés",
    rol: "Tech Lead", dedicacion: "Full time", pais: "México", inicio: "2026-06-25", ptoAcordados: 15,
    licencias: [
      { id: "l0601", tipo: "Vacaciones", desde: "2026-05-05", hasta: "2026-05-09", dias: 5, estado: "Tomada" },
      { id: "l0602", tipo: "Día de estudio / examen", desde: "2026-08-18", hasta: "2026-08-18", dias: 1, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-06-25",
      equipo: 'MacBook Pro 14" M3 Pro', nroSerie: "C02GH4KLMD6T", estado: "Asignado",
      historial: [
        { fecha: "2026-06-25", evento: 'Entrega inicial · MacBook Pro 14"' },
        { fecha: "2026-07-30", evento: "Alta de monitor externo LG 27\" para home office" },
      ],
    },
    seguimientos: [
      { id: "s0601", fecha: "2026-09-05", tipo: "Quincenal", nota: "Lidera bien el squad. Pidió sumar un dev junior al equipo.", responsable: "Andrés", proximo: "2026-09-19" },
      { id: "s0602", fecha: "2026-08-22", tipo: "Quincenal", nota: "Cerró la primera release de telemedicina en fecha.", responsable: "Andrés", proximo: "2026-09-05" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-05", actualizadoPor: "Andrés",
      motivo: "Rol clave, cliente muy conforme con el liderazgo técnico.",
      proximaAccion: "Evaluar ampliación del equipo", proximaAccionFecha: "2026-09-19",
      oportunidad: "Escalar el squad con un dev junior (más facturación)",
    },
    documentos: [
      { id: "d0601", nombre: "Contrato de trabajo", tipo: "Contrato", fecha: "2026-06-25", archivo: "", archivoNombre: "contrato-mateo-herrera.pdf" },
      { id: "d0602", nombre: "INE + CURP", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-06-20", archivo: "", archivoNombre: "ine-curp-mateo-herrera.pdf" },
      { id: "d0603", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-06-10", archivo: "", archivoNombre: "cv-mateo-herrera.pdf" },
      { id: "d0604", nombre: "Constancia de CLABE · BBVA México", tipo: "Constancia de CBU", fecha: "2026-06-21", archivo: "", archivoNombre: "clabe-bbva-mateo.pdf" },
      { id: "d0605", nombre: "Título · Ing. en Sistemas Computacionales", tipo: "Título / Diploma", fecha: "2026-06-22", archivo: "", archivoNombre: "titulo-ing-sistemas-mateo.pdf" },
    ],
    administracion: {
      legajo: "NB-0006", centroCosto: "Delivery · Delta Salud", modalidadPago: "Transferencia bancaria",
      banco: "BBVA México", cuenta: "CLABE 012180001234567895", alias: "mateo.herrera.nb",
      moneda: "MXN", remuneracion: 78000, periodicidad: "Mensual", cobertura: "IMSS + Gastos médicos mayores (GNP)",
      notas: "Tech Lead. Bono trimestral por objetivos del squad.",
    },
  },
  {
    id: "demo-07", creado: "2026-07-01T10:05:00-03:00",
    nombre: "Lucía", apellido: "Ferreyra", estado: "Std By", foto: "",
    documento: "35.190.442", mail: "lucia.ferreyra@notabotagency.es", telefono: "+54 9 351 444 2210",
    direccionCompleta: "Bv. Illia 320, piso 9 A, Nueva Córdoba, Córdoba, Argentina",
    contactoAltNombre: "Marta Ferreyra", contactoAltVinculo: "Madre", contactoAltTelefono: "+54 9 351 444 2299",
    pasaporte: "AAF551903", cuit: "27-35190442-8", linkedin: "https://www.linkedin.com/in/lucia-ferreyra",
    cliente: "Nimbus Logística", proyecto: "Portal B2B", puntoContactoCliente: "Carla Méndez", responsableNotaBot: "Sol",
    rol: "Redactora", dedicacion: "Part time", pais: "Argentina", inicio: "2026-07-01", ptoAcordados: 10,
    licencias: [
      { id: "l0701", tipo: "Vacaciones", desde: "2026-07-28", hasta: "2026-07-30", dias: 3, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-07-01",
      equipo: 'MacBook Air 13" M1', nroSerie: "C02YZ1PLMD8Q", estado: "Devuelto",
      historial: [
        { fecha: "2026-07-01", evento: 'Entrega inicial · MacBook Air 13"' },
        { fecha: "2026-08-18", evento: "Devolución del equipo por pausa del proyecto" },
      ],
    },
    seguimientos: [
      { id: "s0701", fecha: "2026-08-15", tipo: "Puntual", nota: "Proyecto del cliente en pausa. Sin tareas asignadas.", responsable: "Sol", proximo: "2026-09-15" },
      { id: "s0702", fecha: "2026-07-25", tipo: "Mensual", nota: "Entregó la guía de tono y voz del portal. Buen trabajo.", responsable: "Sol", proximo: "2026-08-25" },
    ],
    relacion: {
      estado: "Riesgo de continuidad", ultimaActualizacion: "2026-08-15", actualizadoPor: "Sol",
      motivo: "Proyecto del cliente pausado por tiempo indefinido.",
      proximaAccion: "Confirmar con el cliente si retoma en octubre", proximaAccionFecha: "2026-09-15",
      oportunidad: "Reasignar a contenidos de Faro Educación o Aurora Retail",
    },
    documentos: [
      { id: "d0701", nombre: "Contrato de servicios (freelance)", tipo: "Contrato", fecha: "2026-07-01", archivo: "", archivoNombre: "contrato-lucia-ferreyra.pdf" },
      { id: "d0702", nombre: "DNI (frente y dorso)", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-06-26", archivo: "", archivoNombre: "dni-lucia-ferreyra.pdf" },
      { id: "d0703", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-06-15", archivo: "", archivoNombre: "cv-lucia-ferreyra.pdf" },
      { id: "d0704", nombre: "Constancia de CBU · Banco Nación", tipo: "Constancia de CBU", fecha: "2026-06-27", archivo: "", archivoNombre: "cbu-nacion-lucia.pdf" },
      { id: "d0705", nombre: "Constancia de inscripción monotributo (AFIP)", tipo: "Alta AFIP / Monotributo", fecha: "2026-06-28", archivo: "", archivoNombre: "constancia-monotributo-lucia.pdf" },
    ],
    administracion: {
      legajo: "NB-0007", centroCosto: "Contenido · Nimbus Logística", modalidadPago: "Transferencia bancaria",
      banco: "Banco Nación", cuenta: "0110599520000012345678", alias: "lucia.ferreyra.nb",
      moneda: "ARS", remuneracion: 1200000, periodicidad: "Por entregable", cobertura: "Prepaga particular (Swiss Medical SMG10)",
      notas: "Freelance. Proyecto en pausa desde agosto 2026; sin facturación.",
    },
  },
  {
    id: "demo-08", creado: "2026-07-09T09:00:00-03:00",
    nombre: "Andrés", apellido: "Molina", estado: "Activo", foto: "",
    documento: "50221884K", mail: "andres.molina@notabotagency.es", telefono: "+34 655 12 44 90",
    direccionCompleta: "Calle de Sagasta 18, 4º izq., Chamberí, Madrid, Comunidad de Madrid, España",
    contactoAltNombre: "Elena Molina", contactoAltVinculo: "Hermana", contactoAltTelefono: "+34 655 12 44 99",
    pasaporte: "ESX8842019", cuit: "", linkedin: "https://www.linkedin.com/in/andres-molina",
    cliente: "Helio Fintech", proyecto: "Core Bancario", puntoContactoCliente: "Marta Ledesma", responsableNotaBot: "Fer",
    rol: "Backend Developer", dedicacion: "Full time", pais: "España", inicio: "2026-07-09", ptoAcordados: 22,
    licencias: [
      { id: "l0801", tipo: "Vacaciones", desde: "2026-08-04", hasta: "2026-08-14", dias: 11, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-07-09",
      equipo: 'MacBook Pro 14" M3', nroSerie: "C02FL0PQMD6R", estado: "Asignado",
      historial: [{ fecha: "2026-07-09", evento: 'Entrega inicial · MacBook Pro 14" + token de acceso VPN Helio' }],
    },
    seguimientos: [
      { id: "s0801", fecha: "2026-09-02", tipo: "Mensual", nota: "Sin novedades. Trabajo estable en el core.", responsable: "Fer", proximo: "2026-10-02" },
      { id: "s0802", fecha: "2026-08-01", tipo: "Mensual", nota: "Cerró el módulo de conciliación antes de vacaciones.", responsable: "Fer", proximo: "2026-09-02" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-02", actualizadoPor: "Fer",
      motivo: "Perfil sólido, sin observaciones.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-02",
      oportunidad: "Candidato a referente técnico de la cuenta Helio Fintech",
    },
    documentos: [
      { id: "d0801", nombre: "Contrato de trabajo", tipo: "Contrato", fecha: "2026-07-09", archivo: "", archivoNombre: "contrato-andres-molina.pdf" },
      { id: "d0802", nombre: "DNI / NIE", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-07-03", archivo: "", archivoNombre: "dni-andres-molina.pdf" },
      { id: "d0803", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-06-22", archivo: "", archivoNombre: "cv-andres-molina.pdf" },
      { id: "d0804", nombre: "Certificado de titularidad · CaixaBank", tipo: "Constancia de CBU", fecha: "2026-07-04", archivo: "", archivoNombre: "titularidad-caixabank-andres.pdf" },
    ],
    administracion: {
      legajo: "NB-0008", centroCosto: "Delivery · Helio Fintech", modalidadPago: "Transferencia bancaria",
      banco: "CaixaBank", cuenta: "ES91 2100 0418 4502 0005 1332", alias: "andres.molina.nb",
      moneda: "EUR", remuneracion: 4200, periodicidad: "Mensual", cobertura: "Seguridad Social + Adeslas",
      notas: "Jornada completa. Teletrabajo con 2 días de oficina al mes.",
    },
  },
  {
    id: "demo-09", creado: "2026-07-21T15:30:00-03:00",
    nombre: "Julieta", apellido: "Sosa", estado: "Próximo Ingreso", foto: "",
    documento: "30.774.512", mail: "julieta.sosa@notabotagency.es", telefono: "+54 9 341 233 8890",
    direccionCompleta: "Córdoba 1145, piso 3, Centro, Rosario, Santa Fe, Argentina",
    contactoAltNombre: "Hugo Sosa", contactoAltVinculo: "Padre", contactoAltTelefono: "+54 9 341 233 8899",
    pasaporte: "AAF309887", cuit: "27-30774512-3", linkedin: "https://www.linkedin.com/in/julieta-sosa",
    cliente: "Faro Educación", proyecto: "Campus Online", puntoContactoCliente: "Nicolás Rivas", responsableNotaBot: "Sol",
    rol: "QA Junior", dedicacion: "Part time", pais: "Argentina", inicio: "2026-09-15", ptoAcordados: 10,
    licencias: [
      { id: "l0901", tipo: "Vacaciones", desde: "2026-12-22", hasta: "2026-12-26", dias: 5, estado: "Solicitada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-09-15",
      equipo: 'MacBook Air 13" M2', nroSerie: "C02ZC4RLMDA1", estado: "Pendiente de entrega",
      historial: [{ fecha: "2026-09-08", evento: "Equipo reservado y configurado para el día de ingreso" }],
    },
    seguimientos: [
      { id: "s0901", fecha: "2026-09-01", tipo: "Onboarding", nota: "Contrato enviado. Alta pendiente de firma. Ingreso planificado para el 15/09.", responsable: "Sol", proximo: "2026-09-15" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-01", actualizadoPor: "Sol",
      motivo: "Proceso de alta en curso, sin bloqueos.",
      proximaAccion: "Confirmar ingreso y entrega de equipo", proximaAccionFecha: "2026-09-15",
      oportunidad: "Plan de carrera a QA Semi Senior en 12 meses",
    },
    documentos: [
      { id: "d0901", nombre: "Convenio de pasantía educativa", tipo: "Contrato", fecha: "2026-09-05", archivo: "", archivoNombre: "convenio-pasantia-julieta-sosa.pdf" },
      { id: "d0902", nombre: "DNI (frente y dorso)", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-09-01", archivo: "", archivoNombre: "dni-julieta-sosa.pdf" },
      { id: "d0903", nombre: "Currículum vitae", tipo: "CV", fecha: "2026-08-20", archivo: "", archivoNombre: "cv-julieta-sosa.pdf" },
      { id: "d0904", nombre: "Constancia de CBU · Brubank", tipo: "Constancia de CBU", fecha: "2026-09-02", archivo: "", archivoNombre: "cbu-brubank-julieta.pdf" },
      { id: "d0905", nombre: "Analítico · Tecnicatura en Programación (en curso)", tipo: "Título / Diploma", fecha: "2026-08-25", archivo: "", archivoNombre: "analitico-tecnicatura-julieta.pdf" },
    ],
    administracion: {
      legajo: "NB-0009", centroCosto: "QA · Faro Educación", modalidadPago: "Transferencia bancaria",
      banco: "Brubank", cuenta: "0000076500000012345678", alias: "julieta.sosa.nb",
      moneda: "ARS", remuneracion: 650000, periodicidad: "Mensual", cobertura: "Cobertura de pasantía (Ley 26.427, art. 13)",
      notas: "Pasantía educativa de 6 meses, renovable. Ingreso efectivo 15/09/2026.",
    },
  },
  {
    id: "demo-10", creado: "2026-08-04T12:10:00-03:00",
    nombre: "Tomás", apellido: "Vega", estado: "Inactivo", foto: "",
    documento: "5.117.663-2", mail: "tomas.vega@notabotagency.es", telefono: "+598 99 118 442",
    direccionCompleta: "Rbla. República Argentina 1234, apto. 402, Cordón, Montevideo, Uruguay",
    contactoAltNombre: "Inés Vega", contactoAltVinculo: "Madre", contactoAltTelefono: "+598 99 118 400",
    pasaporte: "D1174820", cuit: "", linkedin: "https://www.linkedin.com/in/tomas-vega",
    cliente: "Vento Media", proyecto: "Rebranding", puntoContactoCliente: "Paula Iglesias", responsableNotaBot: "Joaco",
    rol: "Motion Designer", dedicacion: "Full time", pais: "Uruguay", inicio: "2026-03-03", ptoAcordados: 15,
    licencias: [
      { id: "l1001", tipo: "Vacaciones", desde: "2026-06-16", hasta: "2026-06-20", dias: 5, estado: "Tomada" },
      { id: "l1002", tipo: "Licencia médica", desde: "2026-07-07", hasta: "2026-07-08", dias: 2, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-03-03",
      equipo: 'iMac 24" M3', nroSerie: "C02DR3STMD6V", estado: "Devuelto",
      historial: [
        { fecha: "2026-03-03", evento: 'Entrega inicial · iMac 24" + tableta Wacom Intuos' },
        { fecha: "2026-08-30", evento: "Devolución del equipo por fin de contrato" },
      ],
    },
    seguimientos: [
      { id: "s1001", fecha: "2026-08-25", tipo: "Offboarding", nota: "Cierre de contrato acordado. Último día 30/08. Devolución de equipo coordinada.", responsable: "Joaco", proximo: "2026-09-05" },
      { id: "s1002", fecha: "2026-07-30", tipo: "Mensual", nota: "El cliente adelantó que el rebranding se frena tras esta etapa.", responsable: "Joaco", proximo: "2026-08-25" },
    ],
    relacion: {
      estado: "Riesgo de continuidad", ultimaActualizacion: "2026-08-30", actualizadoPor: "Joaco",
      motivo: "Fin de contrato por recorte de alcance del cliente.",
      proximaAccion: "Baja administrativa y liquidación final", proximaAccionFecha: "2026-09-05",
      oportunidad: "Evaluar recontratación en 2027 si Vento Media retoma el rebranding",
    },
    documentos: [
      { id: "d1001", nombre: "Contrato de servicios", tipo: "Contrato", fecha: "2026-03-03", archivo: "", archivoNombre: "contrato-tomas-vega.pdf" },
      { id: "d1002", nombre: "Cédula de identidad", tipo: "Identificación (DNI/RUT/Cédula)", fecha: "2026-02-26", archivo: "", archivoNombre: "cedula-tomas-vega.pdf" },
      { id: "d1003", nombre: "Currículum vitae + reel", tipo: "CV", fecha: "2026-02-15", archivo: "", archivoNombre: "cv-reel-tomas-vega.pdf" },
      { id: "d1004", nombre: "Constancia de cuenta · BROU", tipo: "Constancia de CBU", fecha: "2026-02-27", archivo: "", archivoNombre: "cuenta-brou-tomas.pdf" },
      { id: "d1005", nombre: "Acuerdo de desvinculación", tipo: "Otro", fecha: "2026-08-30", archivo: "", archivoNombre: "acuerdo-desvinculacion-tomas-vega.pdf" },
    ],
    administracion: {
      legajo: "NB-0010", centroCosto: "Diseño · Vento Media", modalidadPago: "Transferencia bancaria",
      banco: "Banco República (BROU)", cuenta: "UY22 0010 0000 0000 0087 6543", alias: "tomas.vega.nb",
      moneda: "UYU", remuneracion: 88000, periodicidad: "Mensual", cobertura: "FONASA (baja tramitada el 2026-08-30)",
      notas: "Contrato finalizado el 30/08/2026. Liquidación final pagada. Equipo devuelto.",
    },
  },
];
