/* Nómina — dataset de ejemplo (10 colaboradores).
   Se siembra en localStorage la primera vez que se abre el módulo, y se puede
   volver a cargar desde el estado vacío. Borralo cuando cargues datos reales.
   Datos ficticios: nombres, clientes y proyectos son inventados (ISO 27001). */
window.NOMINA_DEMO = [
  {
    id: "demo-01", creado: "2026-04-06T10:00:00-03:00",
    nombre: "Martina", apellido: "Rossi", estado: "Activo", foto: "",
    documento: "32.845.109", mail: "martina.rossi@notabotagency.es", telefono: "+54 9 351 555 0184",
    direccionCompleta: "Av. Rafael Núñez 4250, Córdoba Capital, Córdoba, Argentina",
    contactoAltNombre: "Laura Rossi", contactoAltVinculo: "Hermana", contactoAltTelefono: "+54 9 351 555 0198",
    pasaporte: "", cuit: "27-32845109-4", linkedin: "https://www.linkedin.com/in/martina-rossi",
    cliente: "Facephi", proyecto: "AI Hub", puntoContactoCliente: "Fernando Oteros", responsableNotaBot: "Fer",
    rol: "QA", dedicacion: "Full time", pais: "Argentina", inicio: "2026-04-06",
    ptoAcordados: 15,
    licencias: [
      { id: "l0101", tipo: "Vacaciones", desde: "2026-02-10", hasta: "2026-02-14", dias: 5, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Facephi", fechaEntrega: "2026-04-06",
      equipo: 'MacBook Pro 14"', nroSerie: "FVFGH31Q05MD", estado: "Asignado",
      historial: [{ fecha: "2026-04-06", evento: 'Entrega inicial · MacBook Pro 14" (FVFGH31Q05MD)' }],
    },
    seguimientos: [
      { id: "s0101", fecha: "2026-09-07", tipo: "Mensual", nota: "Conforme con el proyecto. Buena integración con el equipo.", responsable: "Fer", proximo: "2026-10-07" },
      { id: "s0102", fecha: "2026-08-05", tipo: "Mensual", nota: "Sin bloqueos. Solicita revisar objetivos del trimestre.", responsable: "Fer", proximo: "2026-09-07" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-07", actualizadoPor: "Fer",
      motivo: "Buen desempeño e integración con el equipo.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-07",
      oportunidad: "Explorar mayor alcance con cliente",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-02", creado: "2026-05-19T09:30:00-03:00",
    nombre: "Diego", apellido: "Ferreira", estado: "Activo", foto: "",
    documento: "4.982.331", mail: "diego.ferreira@notabotagency.es", telefono: "+598 99 421 337",
    direccionCompleta: "Br. España 2711, apto. 902, Pocitos, Montevideo, Uruguay",
    contactoAltNombre: "Paula Ferreira", contactoAltVinculo: "Pareja", contactoAltTelefono: "+598 99 555 210",
    pasaporte: "", cuit: "", linkedin: "https://www.linkedin.com/in/diego-ferreira",
    cliente: "Nimbus Logística", proyecto: "Portal B2B", puntoContactoCliente: "Carla Méndez", responsableNotaBot: "Joaco",
    rol: "Automation Engineer", dedicacion: "Part time", pais: "Uruguay", inicio: "2026-05-19",
    ptoAcordados: 14,
    licencias: [
      { id: "l0201", tipo: "Vacaciones", desde: "2026-07-14", hasta: "2026-07-18", dias: 5, estado: "Aprobada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-05-19",
      equipo: 'MacBook Air 13"', nroSerie: "C02XR1A2JGH6", estado: "Asignado",
      historial: [{ fecha: "2026-05-19", evento: 'Entrega inicial · MacBook Air 13"' }],
    },
    seguimientos: [
      { id: "s0201", fecha: "2026-08-28", tipo: "Mensual", nota: "Buen ritmo. Automatizó 3 flujos del portal.", responsable: "Joaco", proximo: "2026-09-28" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-08-28", actualizadoPor: "Joaco",
      motivo: "Entregas en fecha, cliente conforme.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-09-28", oportunidad: "",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-03", creado: "2026-06-02T11:15:00-03:00",
    nombre: "Camila", apellido: "Duarte", estado: "Activo", foto: "",
    documento: "3.221.884", mail: "camila.duarte@notabotagency.es", telefono: "+595 981 442 118",
    direccionCompleta: "Dr. Molas López 456, Villa Morra, Asunción, Paraguay",
    contactoAltNombre: "Rosa Duarte", contactoAltVinculo: "Madre", contactoAltTelefono: "+595 981 700 004",
    pasaporte: "PY0482119", cuit: "", linkedin: "https://www.linkedin.com/in/camila-duarte",
    cliente: "Faro Educación", proyecto: "Campus Online", puntoContactoCliente: "Nicolás Rivas", responsableNotaBot: "Sol",
    rol: "Data Analyst", dedicacion: "Full time", pais: "Paraguay", inicio: "2026-06-02",
    ptoAcordados: 15,
    licencias: [
      { id: "l0301", tipo: "Licencia médica", desde: "2026-08-11", hasta: "2026-08-12", dias: 2, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Faro Educación", fechaEntrega: "2026-06-02",
      equipo: 'Dell Latitude 7440', nroSerie: "9QF7X23", estado: "Asignado", historial: [],
    },
    seguimientos: [
      { id: "s0301", fecha: "2026-09-01", tipo: "Mensual", nota: "Observaciones sobre calidad de datos del cliente. Segunda vez que aparece.", responsable: "Sol", proximo: "2026-09-15" },
      { id: "s0302", fecha: "2026-08-01", tipo: "Mensual", nota: "Pidió más contexto de negocio para los reportes.", responsable: "Sol", proximo: "2026-09-01" },
    ],
    relacion: {
      estado: "Requiere atención", ultimaActualizacion: "2026-09-01", actualizadoPor: "Sol",
      motivo: "Observaciones reiteradas sobre alcance y datos del cliente.",
      proximaAccion: "Reunión con el cliente para redefinir alcance", proximaAccionFecha: "2026-09-15",
      oportunidad: "",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-04", creado: "2026-06-10T16:40:00-03:00",
    nombre: "Sebastián", apellido: "Rojas", estado: "Std By", foto: "",
    documento: "16.482.905-1", mail: "sebastian.rojas@notabotagency.es", telefono: "+56 9 6721 0043",
    direccionCompleta: "Av. Providencia 1208, of. 34, Providencia, Santiago, Chile",
    contactoAltNombre: "Ignacio Rojas", contactoAltVinculo: "Hermano", contactoAltTelefono: "+56 9 6721 0099",
    pasaporte: "", cuit: "", linkedin: "https://www.linkedin.com/in/sebastian-rojas",
    cliente: "Vento Media", proyecto: "", puntoContactoCliente: "", responsableNotaBot: "Fer",
    rol: "Consultor SEO", dedicacion: "Part time", pais: "Chile", inicio: "2026-06-10",
    ptoAcordados: 12,
    licencias: [],
    equipamiento: {
      gestion: "Equipo propio del colaborador", clienteResponsable: "", fechaEntrega: "",
      equipo: "Equipo personal", nroSerie: "", estado: "Pendiente de entrega", historial: [],
    },
    seguimientos: [
      { id: "s0401", fecha: "2026-08-20", tipo: "Puntual", nota: "Terminó auditoría SEO. Queda a la espera de nuevo brief del cliente.", responsable: "Fer", proximo: "2026-09-20" },
    ],
    relacion: {
      estado: "Requiere atención", ultimaActualizacion: "2026-08-20", actualizadoPor: "Fer",
      motivo: "Sin proyecto asignado hace 3 semanas.",
      proximaAccion: "Definir nueva asignación o baja temporal", proximaAccionFecha: "2026-09-20",
      oportunidad: "Ofrecer perfil a Aurora Retail",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-05", creado: "2026-06-18T08:50:00-03:00",
    nombre: "Valentina", apellido: "Gómez", estado: "Activo", foto: "",
    documento: "1.014.882.331", mail: "valentina.gomez@notabotagency.es", telefono: "+57 320 448 1120",
    direccionCompleta: "Calle 70 # 11-30, apto. 501, Chapinero, Bogotá, Colombia",
    contactoAltNombre: "Andrea Gómez", contactoAltVinculo: "Hermana", contactoAltTelefono: "+57 320 448 1188",
    pasaporte: "", cuit: "", linkedin: "https://www.linkedin.com/in/valentina-gomez",
    cliente: "Aurora Retail", proyecto: "eCommerce Revamp", puntoContactoCliente: "Diana Salas", responsableNotaBot: "Joaco",
    rol: "Diseñadora UX", dedicacion: "Full time", pais: "Colombia", inicio: "2026-06-18",
    ptoAcordados: 15,
    licencias: [
      { id: "l0501", tipo: "Vacaciones", desde: "2026-09-22", hasta: "2026-09-26", dias: 5, estado: "Solicitada" },
    ],
    equipamiento: {
      gestion: "A cargo del cliente", clienteResponsable: "Aurora Retail", fechaEntrega: "2026-06-18",
      equipo: 'MacBook Pro 16"', nroSerie: "FVFH8K2LQ1P", estado: "Asignado", historial: [],
    },
    seguimientos: [
      { id: "s0501", fecha: "2026-09-03", tipo: "Mensual", nota: "Onboarding completo. Muy buena recepción del equipo de diseño del cliente.", responsable: "Joaco", proximo: "2026-10-03" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-03", actualizadoPor: "Joaco",
      motivo: "Integración muy buena, feedback positivo del cliente.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-03",
      oportunidad: "Sumar horas de research al contrato",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-06", creado: "2026-06-25T13:20:00-03:00",
    nombre: "Mateo", apellido: "Herrera", estado: "Activo", foto: "",
    documento: "HEGM910412HDFRRT08", mail: "mateo.herrera@notabotagency.es", telefono: "+52 55 3410 7788",
    direccionCompleta: "Calle Orizaba 141, int. 3, Roma Norte, Ciudad de México, México",
    contactoAltNombre: "Sofía Herrera", contactoAltVinculo: "Pareja", contactoAltTelefono: "+52 55 3410 7799",
    pasaporte: "G12984771", cuit: "", linkedin: "https://www.linkedin.com/in/mateo-herrera",
    cliente: "Delta Salud", proyecto: "Telemedicina", puntoContactoCliente: "Dra. Luciana Paz", responsableNotaBot: "Andrés",
    rol: "Tech Lead", dedicacion: "Full time", pais: "México", inicio: "2026-06-25",
    ptoAcordados: 15,
    licencias: [
      { id: "l0601", tipo: "Vacaciones", desde: "2026-05-05", hasta: "2026-05-09", dias: 5, estado: "Tomada" },
      { id: "l0602", tipo: "Día de estudio / examen", desde: "2026-08-18", hasta: "2026-08-18", dias: 1, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-06-25",
      equipo: 'MacBook Pro 14"', nroSerie: "C02GH4KLMD6T", estado: "Asignado", historial: [],
    },
    seguimientos: [
      { id: "s0601", fecha: "2026-09-05", tipo: "Quincenal", nota: "Lidera bien el squad. Pidió sumar un dev junior al equipo.", responsable: "Andrés", proximo: "2026-09-19" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-05", actualizadoPor: "Andrés",
      motivo: "Rol clave, cliente muy conforme con el liderazgo técnico.",
      proximaAccion: "Evaluar ampliación del equipo", proximaAccionFecha: "2026-09-19",
      oportunidad: "Escalar squad con un dev junior",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-07", creado: "2026-07-01T10:05:00-03:00",
    nombre: "Lucía", apellido: "Ferreyra", estado: "Std By", foto: "",
    documento: "35.190.442", mail: "lucia.ferreyra@notabotagency.es", telefono: "+54 9 351 444 2210",
    direccionCompleta: "Bv. Illia 320, piso 9 A, Nueva Córdoba, Córdoba, Argentina",
    contactoAltNombre: "Marta Ferreyra", contactoAltVinculo: "Madre", contactoAltTelefono: "+54 9 351 444 2299",
    pasaporte: "", cuit: "27-35190442-8", linkedin: "https://www.linkedin.com/in/lucia-ferreyra",
    cliente: "Nimbus Logística", proyecto: "Portal B2B", puntoContactoCliente: "Carla Méndez", responsableNotaBot: "Sol",
    rol: "Redactora", dedicacion: "Part time", pais: "Argentina", inicio: "2026-07-01",
    ptoAcordados: 10,
    licencias: [],
    equipamiento: {
      gestion: "Equipo propio del colaborador", clienteResponsable: "", fechaEntrega: "",
      equipo: "Equipo personal", nroSerie: "", estado: "Pendiente de entrega", historial: [],
    },
    seguimientos: [
      { id: "s0701", fecha: "2026-08-15", tipo: "Puntual", nota: "Proyecto del cliente en pausa. Sin tareas asignadas.", responsable: "Sol", proximo: "2026-09-15" },
    ],
    relacion: {
      estado: "Riesgo de continuidad", ultimaActualizacion: "2026-08-15", actualizadoPor: "Sol",
      motivo: "Proyecto del cliente pausado por tiempo indefinido.",
      proximaAccion: "Confirmar con el cliente si retoma en octubre", proximaAccionFecha: "2026-09-15",
      oportunidad: "",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-08", creado: "2026-07-09T09:00:00-03:00",
    nombre: "Andrés", apellido: "Molina", estado: "Activo", foto: "",
    documento: "50221884K", mail: "andres.molina@notabotagency.es", telefono: "+34 655 12 44 90",
    direccionCompleta: "Calle de Sagasta 18, 4º izq., Chamberí, Madrid, España",
    contactoAltNombre: "Elena Molina", contactoAltVinculo: "Hermana", contactoAltTelefono: "+34 655 12 44 99",
    pasaporte: "", cuit: "", linkedin: "https://www.linkedin.com/in/andres-molina",
    cliente: "Helio Fintech", proyecto: "Core Bancario", puntoContactoCliente: "Marta Ledesma", responsableNotaBot: "Fer",
    rol: "Backend Developer", dedicacion: "Full time", pais: "España", inicio: "2026-07-09",
    ptoAcordados: 22,
    licencias: [
      { id: "l0801", tipo: "Vacaciones", desde: "2026-08-04", hasta: "2026-08-14", dias: 11, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-07-09",
      equipo: 'MacBook Pro 14"', nroSerie: "C02FL0PQMD6R", estado: "Asignado", historial: [],
    },
    seguimientos: [
      { id: "s0801", fecha: "2026-09-02", tipo: "Mensual", nota: "Sin novedades. Trabajo estable en el core.", responsable: "Fer", proximo: "2026-10-02" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-02", actualizadoPor: "Fer",
      motivo: "Perfil sólido, sin observaciones.",
      proximaAccion: "Seguimiento mensual", proximaAccionFecha: "2026-10-02", oportunidad: "",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-09", creado: "2026-07-21T15:30:00-03:00",
    nombre: "Julieta", apellido: "Sosa", estado: "Próximo Ingreso", foto: "",
    documento: "30.774.512", mail: "julieta.sosa@notabotagency.es", telefono: "+54 9 341 233 8890",
    direccionCompleta: "Córdoba 1145, piso 3, Centro, Rosario, Santa Fe, Argentina",
    contactoAltNombre: "Hugo Sosa", contactoAltVinculo: "Padre", contactoAltTelefono: "+54 9 341 233 8899",
    pasaporte: "", cuit: "27-30774512-3", linkedin: "https://www.linkedin.com/in/julieta-sosa",
    cliente: "Faro Educación", proyecto: "Campus Online", puntoContactoCliente: "Nicolás Rivas", responsableNotaBot: "Sol",
    rol: "QA Junior", dedicacion: "Part time", pais: "Argentina", inicio: "2026-09-15",
    ptoAcordados: 10,
    licencias: [],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-09-15",
      equipo: 'MacBook Air 13" (reservado)', nroSerie: "", estado: "Pendiente de entrega", historial: [],
    },
    seguimientos: [
      { id: "s0901", fecha: "2026-09-01", tipo: "Onboarding", nota: "Contrato enviado. Alta pendiente de firma. Ingreso planificado para el 15/09.", responsable: "Sol", proximo: "2026-09-15" },
    ],
    relacion: {
      estado: "Todo en orden", ultimaActualizacion: "2026-09-01", actualizadoPor: "Sol",
      motivo: "Proceso de alta en curso, sin bloqueos.",
      proximaAccion: "Confirmar ingreso y entrega de equipo", proximaAccionFecha: "2026-09-15", oportunidad: "",
    },
    documentos: [], administracion: {},
  },
  {
    id: "demo-10", creado: "2026-08-04T12:10:00-03:00",
    nombre: "Tomás", apellido: "Vega", estado: "Inactivo", foto: "",
    documento: "5.117.663", mail: "tomas.vega@notabotagency.es", telefono: "+598 99 118 442",
    direccionCompleta: "Rbla. República Argentina 1234, apto. 402, Cordón, Montevideo, Uruguay",
    contactoAltNombre: "Inés Vega", contactoAltVinculo: "Madre", contactoAltTelefono: "+598 99 118 400",
    pasaporte: "PY1174820", cuit: "", linkedin: "https://www.linkedin.com/in/tomas-vega",
    cliente: "Vento Media", proyecto: "Rebranding", puntoContactoCliente: "Paula Iglesias", responsableNotaBot: "Joaco",
    rol: "Motion Designer", dedicacion: "Full time", pais: "Uruguay", inicio: "2026-03-03",
    ptoAcordados: 15,
    licencias: [
      { id: "l1001", tipo: "Vacaciones", desde: "2026-06-16", hasta: "2026-06-20", dias: 5, estado: "Tomada" },
    ],
    equipamiento: {
      gestion: "A cargo de Not a Bot", clienteResponsable: "", fechaEntrega: "2026-03-03",
      equipo: 'iMac 24"', nroSerie: "C02DR3STMD6V", estado: "Devuelto",
      historial: [
        { fecha: "2026-03-03", evento: 'Entrega inicial · iMac 24"' },
        { fecha: "2026-08-30", evento: "Devolución por fin de contrato" },
      ],
    },
    seguimientos: [
      { id: "s1001", fecha: "2026-08-25", tipo: "Offboarding", nota: "Cierre de contrato acordado. Último día 30/08. Devolución de equipo coordinada.", responsable: "Joaco", proximo: "" },
    ],
    relacion: {
      estado: "Riesgo de continuidad", ultimaActualizacion: "2026-08-30", actualizadoPor: "Joaco",
      motivo: "Fin de contrato por recorte de alcance del cliente.",
      proximaAccion: "Baja administrativa completada", proximaAccionFecha: "", oportunidad: "",
    },
    documentos: [], administracion: {},
  },
];
