// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js usa .env.local por convencion; se centraliza ahi en vez de duplicar en .env
dotenv.config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // conexión directa (5432), usada solo por el CLI para migrate/introspect.
    // el cliente en runtime usa DATABASE_URL (pooler) via el driver adapter en src/lib/prisma.ts
    url: process.env["DIRECT_URL"],
  },
});
