/* Pipeline — dataset de ejemplo (14 leads).
   Se siembra en localStorage la primera vez que se abre el módulo.
   Borralo (y su <script> en index.html) al conectar el CRM real. */
window.PIPELINE_DEMO = [
  { id: "d01", contacto: "Lucía Sanabria", empresa: "Fintech Delta", email: "lucia@fintechdelta.uy", telefono: "+598 99 123 456", origen: "Web", servicio: "Externalización de talento", etapa: "nuevo", responsable: "Sofía Ramos", proximaAccion: "Primer contacto por mail", proximaFecha: "2026-09-02", creado: "2026-08-27", actividad: [{ fecha: "2026-08-27", tipo: "Nota", detalle: "Entró por el formulario de la web. Pide 3 devs backend." }] },
  { id: "d02", contacto: "Marcos Beltrán", empresa: "Agrotech Sur", email: "mbeltran@agrotechsur.com", telefono: "+54 341 555 0192", origen: "LinkedIn", servicio: "Transformación digital", etapa: "nuevo", responsable: "Nicolás Duarte", proximaAccion: "", proximaFecha: "", creado: "2026-08-28", actividad: [] },
  { id: "d03", contacto: "Renata Villalba", empresa: "Clínica Norte", email: "rvillalba@clinicanorte.py", telefono: "+595 981 447 220", origen: "Referido", servicio: "Contratación directa", etapa: "contactado", responsable: "Sofía Ramos", proximaAccion: "Llamada de descubrimiento", proximaFecha: "2026-08-29", creado: "2026-08-20", actividad: [{ fecha: "2026-08-22", tipo: "Email", detalle: "Presentación enviada. Respondió pidiendo llamada." }] },
  { id: "d04", contacto: "Diego Fuentes", empresa: "LogiCorp", email: "dfuentes@logicorp.cl", telefono: "+56 2 2987 1100", origen: "Evento", servicio: "Externalización de talento", etapa: "contactado", responsable: "Nicolás Duarte", proximaAccion: "Enviar case studies de logística", proximaFecha: "2026-09-03", creado: "2026-08-19", actividad: [{ fecha: "2026-08-18", tipo: "Reunión", detalle: "Charla en stand del evento. Interesado en squad de datos." }] },
  { id: "d05", contacto: "Ana Rey", empresa: "EduPlus", email: "ana.rey@eduplus.es", telefono: "+34 911 22 33 44", origen: "Outbound", servicio: "Transformación digital", etapa: "calificado", responsable: "Sofía Ramos", proximaAccion: "Agendar demo técnica", proximaFecha: "2026-09-01", creado: "2026-08-10", actividad: [{ fecha: "2026-08-12", tipo: "Llamada", detalle: "Call de calificación. Presupuesto confirmado para Q4." }, { fecha: "2026-08-20", tipo: "Email", detalle: "Mandó requerimientos técnicos." }] },
  { id: "d06", contacto: "Tomás Iriarte", empresa: "RetailMax", email: "tiriarte@retailmax.com.ar", telefono: "+54 11 4555 8080", origen: "Referido", servicio: "Externalización de talento", etapa: "calificado", responsable: "Martín Vega", proximaAccion: "Definir perfiles con el CTO", proximaFecha: "2026-09-04", creado: "2026-08-11", actividad: [{ fecha: "2026-08-14", tipo: "Reunión", detalle: "Reunión inicial. Necesitan 2 frontend + 1 QA." }] },
  { id: "d07", contacto: "Valeria Cardozo", empresa: "HealthSync", email: "vcardozo@healthsync.co", telefono: "+57 1 508 9000", origen: "Web", servicio: "Contratación directa", etapa: "propuesta", responsable: "Nicolás Duarte", proximaAccion: "Follow-up de la propuesta", proximaFecha: "2026-08-28", creado: "2026-07-30", actividad: [{ fecha: "2026-08-05", tipo: "Reunión", detalle: "Presentación de propuesta por Meet." }, { fecha: "2026-08-08", tipo: "Email", detalle: "Enviada propuesta formal en PDF." }] },
  { id: "d08", contacto: "Federico Lima", empresa: "PagoYa", email: "flima@pagoya.com.br", telefono: "+55 11 3030 4040", origen: "LinkedIn", servicio: "Transformación digital", etapa: "propuesta", responsable: "Sofía Ramos", proximaAccion: "Reunión con el CFO", proximaFecha: "2026-09-03", creado: "2026-07-22", actividad: [{ fecha: "2026-08-01", tipo: "Reunión", detalle: "Workshop de alcance. Migración de core a microservicios." }, { fecha: "2026-08-15", tipo: "Email", detalle: "Propuesta enviada, en revisión interna." }] },
  { id: "d09", contacto: "Camila Ortega", empresa: "MobiliT", email: "cortega@mobilit.mx", telefono: "+52 55 1234 5678", origen: "Evento", servicio: "Externalización de talento", etapa: "negociacion", responsable: "Martín Vega", proximaAccion: "Ajustar scope y precio", proximaFecha: "2026-09-02", creado: "2026-07-05", actividad: [{ fecha: "2026-07-28", tipo: "Reunión", detalle: "Propuesta aceptada en principio, negocian 6 vs 8 personas." }, { fecha: "2026-08-20", tipo: "Llamada", detalle: "Piden descuento por volumen." }] },
  { id: "d10", contacto: "Joaquín Peña", empresa: "DataBridge", email: "jpena@databridge.com.ar", telefono: "+54 11 4777 2020", origen: "Referido", servicio: "Transformación digital", etapa: "negociacion", responsable: "Nicolás Duarte", proximaAccion: "Enviar contrato para firma", proximaFecha: "2026-09-05", creado: "2026-06-28", actividad: [{ fecha: "2026-08-18", tipo: "Reunión", detalle: "Acordado alcance y equipo. Falta OK legal." }] },
  { id: "d11", contacto: "Soledad Miranda", empresa: "TelcoOne", email: "smiranda@telcoone.uy", telefono: "+598 2 900 1234", origen: "Referido", servicio: "Externalización de talento", etapa: "ganado", responsable: "Sofía Ramos", proximaAccion: "", proximaFecha: "", creado: "2026-06-01", actividad: [{ fecha: "2026-08-12", tipo: "Nota", detalle: "Contrato firmado. Arranca squad de 5 el 1/9." }] },
  { id: "d12", contacto: "Bruno Acosta", empresa: "GreenFin", email: "bacosta@greenfin.es", telefono: "+34 934 00 11 22", origen: "Web", servicio: "Contratación directa", etapa: "ganado", responsable: "Martín Vega", proximaAccion: "", proximaFecha: "", creado: "2026-06-15", actividad: [{ fecha: "2026-08-05", tipo: "Nota", detalle: "Cerró búsqueda de Head of Data. Facturado." }] },
  { id: "d13", contacto: "Paula Godoy", empresa: "QuickShip", email: "pgodoy@quickship.cl", telefono: "+56 9 8888 7777", origen: "Outbound", servicio: "Externalización de talento", etapa: "perdido", responsable: "Nicolás Duarte", proximaAccion: "", proximaFecha: "", motivoPerdida: "Precio", creado: "2026-06-20", actividad: [{ fecha: "2026-07-30", tipo: "Email", detalle: "Eligieron un proveedor local más barato." }] },
  { id: "d14", contacto: "Iván Torres", empresa: "LegalTech BA", email: "itorres@legaltechba.com", telefono: "+54 11 4123 9090", origen: "LinkedIn", servicio: "Transformación digital", etapa: "perdido", responsable: "Sofía Ramos", proximaAccion: "", proximaFecha: "", motivoPerdida: "Timing", creado: "2026-05-30", actividad: [{ fecha: "2026-07-10", tipo: "Llamada", detalle: "Frenan el proyecto hasta 2027 por reestructuración." }] },
];
